# Generated by Django 2.2.6 on 2019-10-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batting_average', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.PositiveIntegerField()),
                ('batting_team', models.CharField(max_length=100)),
                ('bowling_team', models.CharField(max_length=100)),
                ('over', models.PositiveIntegerField()),
                ('ball', models.PositiveIntegerField()),
                ('batsman', models.CharField(max_length=100, null=True)),
                ('non_striker', models.CharField(max_length=100, null=True)),
                ('bowler', models.CharField(max_length=100, null=True)),
                ('is_super_over', models.PositiveIntegerField()),
                ('wide_runs', models.PositiveIntegerField()),
                ('bye_runs', models.PositiveIntegerField()),
                ('legbye_runs', models.PositiveIntegerField()),
                ('noball_runs', models.PositiveIntegerField()),
                ('penalty_runs', models.PositiveIntegerField()),
                ('batsman_runs', models.PositiveIntegerField()),
                ('extra_runs', models.PositiveIntegerField()),
                ('total_runs', models.PositiveIntegerField()),
                ('player_dismissed', models.CharField(max_length=50, null=True)),
                ('dismissal_kind', models.CharField(max_length=50, null=True)),
                ('fielder', models.CharField(max_length=50, null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batting_average.Matches')),
            ],
        ),
    ]
